import { test, expect } from '@playwright/test';
test('선택, 기록 저장 및 삭제가 동작한다', async ({ page }) => {
 const errors = []; page.on('pageerror', e => errors.push(e.message));
 await page.goto('/');
 await page.getByRole('button', { name: '하나 골라줘', exact: true }).click();
 await expect(page.getByRole('alert')).toContainText('두 개 이상');
 await page.getByLabel('선택지 1', { exact: true }).fill('파스타');
 await page.getByLabel('선택지 2', { exact: true }).fill('초밥');
 await page.getByRole('button', { name: '하나 골라줘', exact: true }).click();
 await expect(page.getByRole('dialog')).toBeVisible();
 await expect(page.locator('#result-title')).toHaveText(/^(파스타|초밥)$/);
 await page.getByRole('button', { name: '좋아, 이걸로 할래' }).click();
 await page.reload();
 await page.getByRole('button', { name: '내 선택 기록', exact: true }).click();
 await expect(page.locator('.history-item')).toHaveCount(1);
 page.on('dialog', dialog => dialog.accept());
 await page.getByRole('button', { name: '기록 모두 지우기' }).click();
 await expect(page.getByText('아직 선택 기록이 없어요.')).toBeVisible();
 expect(errors).toEqual([]);
});
test('템플릿과 선택지 편집, 화면 크기가 정상이다', async ({ page }, testInfo) => {
 await page.goto('/');
 await page.getByRole('button', { name: /오늘 뭐 먹지/ }).click();
 await expect(page.getByLabel('선택지 1', { exact: true })).toHaveValue('파스타');
 await page.getByRole('button', { name: '선택지 추가하기' }).click();
 await expect(page.getByLabel('선택지 5', { exact: true })).toBeVisible();
 await page.getByRole('button', { name: '선택지 5 삭제' }).click();
 await expect(page.getByLabel('선택지 5', { exact: true })).toHaveCount(0);
 const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
 expect(overflow).toBe(false);
 await page.screenshot({ path: `/tmp/icanpick-${testInfo.project.name}.png`, fullPage: true });
});
test('초안 복원, 선택 확정, 새로운 고민을 시작한다', async ({ page }) => {
 await page.goto('/');
 await page.getByLabel('고민의 제목').fill('주말 계획');
 await page.getByLabel('선택지 1', { exact: true }).fill('산책');
 await page.getByLabel('선택지 2', { exact: true }).fill('영화');
 await page.reload();
 await expect(page.getByLabel('고민의 제목')).toHaveValue('주말 계획');
 await expect(page.getByLabel('선택지 1', { exact: true })).toHaveValue('산책');
 await page.getByRole('button', { name: '하나 골라줘', exact: true }).click();
 await page.keyboard.press('Shift+Tab');
 await expect(page.getByRole('button', { name: '한 번 더 골라보기' })).toBeFocused();
 await page.keyboard.press('Tab');
 await expect(page.getByRole('button', { name: '결과 닫기' })).toBeFocused();
 await page.getByRole('button', { name: '좋아, 이걸로 할래' }).click();
 await expect(page.locator('.accepted strong')).toHaveText(/^(산책|영화)$/);
 await expect(page.getByRole('button', { name: '하나 골라줘', exact: true })).toBeFocused();
 await page.getByRole('button', { name: '새로운 고민 시작하기' }).click();
 await expect(page.getByLabel('고민의 제목')).toBeEmpty();
 await expect(page.getByLabel('고민의 제목')).toBeFocused();
 await expect(page.getByLabel('선택지 1', { exact: true })).toBeEmpty();
});
test('손상된 로컬 기록도 앱 실행을 막지 않는다', async ({ page }) => {
 await page.addInitScript(() => localStorage.setItem('icanpick-history', '[null,{"date":"bad","result":"x"}]'));
 await page.goto('/');
 await page.getByRole('button', { name: '내 선택 기록', exact: true }).click();
 await expect(page.getByText('아직 선택 기록이 없어요.')).toBeVisible();
});
test('개인정보 안내에서 초안과 기록을 함께 삭제한다', async ({ page }) => {
 await page.goto('/');
 await page.getByLabel('선택지 1', { exact: true }).fill('파스타');
 await page.getByLabel('선택지 2', { exact: true }).fill('초밥');
 await page.getByRole('button', { name: '하나 골라줘', exact: true }).click();
 await page.getByRole('button', { name: '좋아, 이걸로 할래' }).click();
 await page.getByRole('button', { name: '앱·개인정보 안내' }).click();
 await expect(page.getByRole('heading', { name: '무엇을 저장하나요?' })).toBeVisible();
 page.on('dialog', dialog => dialog.accept());
 await page.getByRole('button', { name: '선택지와 기록 모두 지우기' }).click();
 await expect(page.getByRole('status')).toContainText('삭제했어요');
 await page.reload();
 await expect(page.getByLabel('선택지 1', { exact: true })).toBeEmpty();
 await page.getByRole('button', { name: '내 선택 기록', exact: true }).click();
 await expect(page.getByText('아직 선택 기록이 없어요.')).toBeVisible();
});
